### ISSUE TITLE
High CPU usage on server

### ISSUE THREAD

**Issue by Zalkortis** [AllTheMods/ATM-5#102]
I don't know if this is related to All the mods 5 but I have this only with this modpack. But didn't try other 1.15 packs so far. 

When I start up a server, in a linux vm, 4GB RAM with 2 cores, it uses 100% CPU all the time, both CPUs are at capacity. I have no lag in game, but this doesn't seem right. Even when I disconnect from the server, it has 100% CPU usage. 

I have tried this with CentOS 7 as well as CentOS 8, same experience. 

When I shutdown the server, it also seems that one Java instance doesn't gracefully end. It still caps one core at 100% even when the server isn't even running anymore. 

I can reproduce this with every fresh VM I set up with All the mods 5. So far only have experience with 1.12.2 mod packs, I also run quite huge packs with almost 240 mods like revelation without any issues. With 1.12 packs I have like like 20-40% CPU when playing with 2-3 players.

The VMs running on a Xeon with 4 cores at 3.7GHz and I have 32GB RAM available. 

Any idea would be much appreciated how to get over this. Would really like to play this pack but it seems wrong  that it's using all the cpu power it gets. :-)

**Comment by lucasvanhalst** [comment]
Try giving it more RAM. I had the same issue on my rather underpowered server (dual core Pentium from 2015 / 8GB ram). I thought, surely 4GB should be enough but only after assigning 5.5GB to the vm and 5GB to the java process it ran as I expected, which is about 15% cpu usage at idle. Otherwise it was also pinned at 100% regardless of what I was doing.

**Comment by ovingiv** [comment]
When I was experimenting with VMs and Minecraft servers I noticed a lot of lag in general with just vanilla Minecraft while it was running on a VM having used both FreeNAS and Proxmox, so that might be your issue. I stopped trying to run my servers on a VM. I'm going to guess you have a E5-1620 v2. 

I have a Dell 410 with dual x5670(s) and 64gb of ram. I also give all of my servers 10gb of ram to work with.

I'm just giving you my 2 cents with my own findings.

**Comment by LtLolFace** [comment]
When launching the server make sure the start file has the variables -Xms 4000M -Xmx 8000M after -d64 and before -jar. This will stop the java from full garbage collection until it reaches 4 GB ram, and limits the total available ram to 8 GB. You can of course tweak to your liking. Hope this helps!
