### ISSUE TITLE
Unlimited Power Dupe with POWAH

### ISSUE THREAD

**Issue by skyfirebro** [AllTheMods/ATM-5#136]
Using the cables and energy cells you are able to create unlimited power

## Expected Behavior
Stacking Energy Cells together should just drain and push to the nearest most empty source. It does not. So instead I connected all with cables expecting the cables to act as the pathway the cells could not push/pull already.

## Current Behavior
The blocks do not drain power. Instead it creates a unlimited loop and just powers everything without needing to generate more power.

## Steps to Reproduce

1. Put 6 energy cells together 2x3 and connect all from with cable.
2. Power it from from the cables

**Comment by vidiot5533** [comment]
I would also note that even a single energy cell has it's issues. placing a block that uses FE instead of RF and exceeds the energy production (so long as it has some production) will drain the energy cell to 0, but the block itself will still be powered. all RF powered blocks work as intended, no power in energy cell=little to no power to those blocks

**Comment by oly2o6** [comment]
bug for the mod developer, please make sure this is reported to their github
