### ISSUE TITLE
game crash with Xnet Connector and any Maschine from Industrial Foregoing

### ISSUE THREAD

**Issue by saovenn** [AllTheMods/ATM-5#148]
## Expected Behavior
If you remove the Connector / Advanced Connector the game should not crash.

## Current Behavior
If you place a Connector / Advanced Connector from Xnet on any Machine from Industrial Foregoing (tested on Plant Sower, Plant Gatherer and Dissolution Chamber) and try to remove it (left click) the game crashes instant.

## Steps to Reproduce
1. place the Xnet Connector on any machine from Industrial Foregoing
2. place the Connector / Advanced Connector on the machine
3. left-click with any pickaxe the connector
4. instantly crashes

## Log
https://pastebin.com/YBsdwqav

video: 
https://drive.google.com/uc?id=1OjshlNOPcAfFpnmXW-GskSIXiOQTKGnA
(only 1 left click is needed to crash the game)

**Comment by Immersi0nn** [comment]
Same issue here, it's any xnet cable even unconnected, the only way to remove them is through creative. The problem seems related to the visual effect of block breaking. The easy fix is just to downgrade Xnet to 'xnet-1.15-2.1.3-beta.jar' since the 2.1.4 version seems to be bugged with this problem.

**Comment by Piratkopia13** [comment]
I have the same issue. Any nearby player also seems to crash.

It is possible to break the cable/connector using any block breaker!

**Comment by whatthedrunk** [comment]
About to push a new update ill make sure this is downgraded for now thanks!
