### ISSUE TITLE
Ocean Monuments don't generate when BoP is used

### ISSUE THREAD

**Issue by ChromeMystic** [AllTheMods/ATM-5#15]
Whenever a Map is generated with BoP no Ocean Monuments are created - with Vanilla worldgen they are created as expected.

I tested a number of seeds and searched for the monuments with the /locate command.

I am not sure if it is a BoP problem or a Problem with another mod interacting with BoP

**Comment by 0xicl33n** [comment]
Same problem!

```
ATM5 Version: 1.2
Minecraft Version: 1.15.2
forge-31.1.0
```

**Comment by darkyth** [comment]
I am also experiencing this issue. Same versions listed above.

**Comment by darkyth** [comment]
There are a few issues about this on the Biomes o Plenty GitHub as well.

https://github.com/Glitchfiend/BiomesOPlenty/issues/1528
https://github.com/Glitchfiend/BiomesOPlenty/issues/1531
https://github.com/Glitchfiend/BiomesOPlenty/issues/1535

The one issue that received a reply said it is likely a Forge issue. I wonder if it is related to the Advanced Mining Dimension mod not working on a Biomes O' Plenty generated world, because it does work on a Default generated world.
