### ISSUE TITLE
Can not see how to generate world type: Lost Cities

### ISSUE THREAD

**Issue by ircmaan** [AllTheMods/ATM-5#18]
SUBJ

**Comment by jolandepoel** [comment]
In newer Minecraft versions (I've seen it in 1.14.4 and 1.15.2) the Lost Cities mod works a little differently. Instead of adding a new world type, like Biomes O' Plenty does, Lost Cities is an option in the upper right-hand corner of your screen during world creation. 

1) After clicking 'Create New World' You need to click 'More World Options...'
2) Choose any world type (Biomes O' Plenty if you're playing ATM-5) and click the Cities button in the upper right-hand corner. 
2) Click the button (it initially says 'Disabled') to cycle through profiles until it has the profile you prefer, click 'Done'.
'rarecities' is what I generally play with, but you can try any of the profiles. The little preview box shows roughly the amount of cities to landscape. It takes a little loading time between profiles, especially just before the 'onlycities' profile.
3) Choose your other options (Cheats, chest, etc.) Click 'Done'
4) Give your world a name and click 'Create New World', your world will generate with the world type AND cities profile you have selected. 

I hope that helps!

**Comment by ircmaan** [comment]
Thanx! I've done it :)
