### ISSUE TITLE
Crash when loading forge

### ISSUE THREAD

**Issue by PokeDraco** [AllTheMods/ATM-5#202]
When i'm trying to launch ATM 5 from the Twitch launcher, the game will crash at the second i click on "play" and will leave this error : 
![image](https://user-images.githubusercontent.com/68465629/87851355-4303f980-c8f8-11ea-83c7-96b8262ff373.png)

Do you know how to fix it please ? 
I tried to download previous version and there's still the same problem

**Comment by sgtspanky01** [comment]
I'm having this same problem. It seems the server zip does not have Forge packed in it or has the wrong version. i have downloaded the version mentioned in the error report, but then I get a mod version error (red cross by the server) when i try to join. not sure what the issue is now but I have had this problem several times with different modded servers, but only from Twitch as a source
p.s. you can get the correct forge version from their download page (https://files.minecraftforge.net/)
match up the version numbers, download the installer and install it to the "install" folder mentioned in your post above
i.e. Twitch\Minecraft\Install\
It will auto put the files where they need to go after that

**Comment by oly2o6** [comment]
this is usually an issue with twitch, trying an alternative launcher such as multimc or gdlauncher usually gets around this issue from occuring
