### ISSUE TITLE
Crash in new IE ver

### ISSUE THREAD

**Issue by kiryD** [AllTheMods/ATM-5#260]
## Expected Behavior

Blueprint just have to be in table

## Current Behavior

Game crashed

## Possible Solution

delete ie

## Steps to Reproduce

1. Download new ie for 1.19.3
2. Place down eng table
3. Place blueprint in
4. Game crash

## Log

https://gist.github.com/BlueOakOfficial/2e99b839b69072cc0e04e89d1a27e115

## Detailed Description

Just crash with -1 code

**Comment by Mitchell5200** [comment]
First of all, ATM5 is a 1.15 pack, and your log appears to be for a 1.19.3 test server you've made.
Second of all, Optifine is known to break mods, remove it, *(the IE devs will tell you the same when you report this to them)*
I recommend you use Rubidium instead of optifine in modded MC from now on.
https://github.com/BluSunrize/ImmersiveEngineering/issues
