### ISSUE TITLE
natures aura corrupting

### ISSUE THREAD

**Issue by jayjones87** [AllTheMods/ATM-5#30]
planted the ancient sapling from natures aura and its corrupted the chunk it was placed in https://pastebin.com/kjN7J7xH

(reporting on the mods bug tracker, this is a fyi)

**Comment by ogmacwinux** [comment]
I encountered the same error. Opening the save immediately crashes the client. 

Workaround is to disable Fast Leaf Decay and let all the leaf blocks decay naturally. You can re-enable it afterwards, just don't plant or chop down an Ancient Tree.

Issue has already been opened on Fast Leaf Decay's tracker since Jan 28: https://github.com/Olafski/FastLeafDecay/issues/27

**Comment by Quarris** [comment]
Unfortunately that looks like that repo is no longer open source, so I can't even check why they are doing this.

**Comment by whatthedrunk** [comment]
This should be fixed as fast leaf decay was removed from the pack.
