### ISSUE TITLE
Silent Gear Mattock creating dirt paths instead of farmland and turns grass into farmland

### ISSUE THREAD

**Issue by seanimusprime** [AllTheMods/ATM-5#51]
The Silent Gear Mattock creates dirt paths when used on dirt and turns grass into farmland.

**Comment by redaktiv** [comment]
And turns dirt paths into farmland

**Comment by SnackyWell** [comment]
It is a good way just use it 2x and you have your farmland

**Comment by Martin-Astos** [comment]
I can no longer find where I read this but I am as high as 99% certain that this is a feature of Silent Gear's Mattocks?

**Comment by redcatone** [comment]
I think this might actually be a interaction/feature of [quark](https://quark.vazkii.net/#features) and mattocks from silent's gear.
![image](https://user-images.githubusercontent.com/24564581/79672207-828c4e00-8202-11ea-80fd-6a0bbd402ed7.png)
Because mattocks act as a shovel, axe, and hoe they make path from dirt but can also till it to make farmland.

**Comment by whatthedrunk** [comment]
This is fixed in the new 1.18b beta thanks!
