### ISSUE TITLE
CPU load spikes in 1.15

### ISSUE THREAD

**Issue by AlpBilgin** [AllTheMods/ATM-5#65]
## Expected Behavior
In release 1.13 CPU usage is flatter, gameplay is smooth: http://prntscr.com/rv8vmd

## Current Behavior
In release 1.15 CPU usage is jagged spikes cause jerky gameplay: http://prntscr.com/rv8wuv

## Possible Solution
Maybe temporarily remove the offending mod?

## Steps to Reproduce

1. Install 1.15
2. Login to a compatible server
3. experience jerky gameplay

**Comment by AlpBilgin** [comment]
It turns out Twitch client wasn't allocating enough ram to the MC instance. Therefore, this is no bug.

**Comment by AlpBilgin** [comment]
https://www.reddit.com/r/allthemods/comments/fur8q8/installed_atm5_but_its_locking_up_every_few/

**Comment by flubbes** [comment]
In my opinion, this could be still unwanted behaviour, because:

* Yes, it gets _better_ when allocating more RAM
* The problem then still persists. It doesn't freeze the client but reduces FPS to ~30% for a few seconds

Though I don't know if this is an ATM5 mod combination Problem or just a single mod which causes the issues. The devs probably can shed a light on this.

The players on my server are experiencing performance anomalies like that.
On slower systems, this problem gets more game-changing. 

I'm 95 % sure the problem you have stated could relate to my observations.

**Comment by AlpBilgin** [comment]
I agree that it's bad, but it isn't necessarily a ATM5 problem. It should eventually land in a mod developer's lap.
