### ISSUE TITLE
Inventory lost

### ISSUE THREAD

**Issue by TheLonelyKid159** [AllTheMods/ATM-5#70]
When my I middle mouse clicked in a modular storage, my entire inventory disappeared and the items inside either went into my inventory or disappeared.

**Comment by HowardRoark2016** [comment]
I came here to post a similar problem. I was playing with All The Mods 5 (which was up to version 1.15 when the issue occured on Sunday, April 12, 2020) which was using "rftoolsbase-1.15-1.0.1-alpha" and "rftoolsutility-1.15-2.0.1-alpha". It also uses "rftoolsstorage-1.15-1.0.3-alpha" which contains the "Modular Storage" block referenced in the opening post of this thread.

However, my issue was with RFToolsUtility Crafter Tier 3 block. I was looking at the Crafter's GUI when I accidentally middle-mouse-clicked on my inventory. Everything in my inventory including the items in my hotbar went into the spaces of the Crafter's GUI, including into the 3x3 spaces of the Crafter's crafting grid. I was able to pull out my items from the Crafter's inventory, but the nine items that appeared in the Crafter's 3x3 crafting grid simply disappeared when I clicked on them to remove them.

I thought perhaps this might be an Inventory Sorter Mod issue. In case that is the problem, the mod pack was using "inventorysorter-1.15.2-17.0.0" at the time of the issue.

**Comment by darkluzer** [comment]
Maybe the issue is with the "trash bin" below the inventory, so when you middle click everything goes to that trash bin, but I am not sure about it
The same happened with upgrades in the Industrial Foregoing machines, if you middle click in the upgrade slots the upgrades will disappear.

**Comment by HowardRoark2016** [comment]
> Maybe the issue is with the "trash bin" below the inventory, so when you middle click everything goes to that trash bin, but I am not sure about it

That's not what happens. The items don't instantly disappear after middle-mouse-clicking on them. Imagine the RFTools Crafter GUI. It's completely empty, no items in its storage area and no recipes remembered in the crafting grid. You have items in your hot bar. If you middle-mouse-click on one of your items, all the items instantly transfer from your inventory to the nine squares of the Crafter's crafting grid with the rest of your items appearing in the squares of the Crafter's storage area. You can see all of your items in the Crafter's GUI. Naturally, you want your stuff back, so you left-mouse-click to pick up the item so that you can place the item into your inventory or hot bar. You can do precisely that for all of your items that moved into the Crafter's inventory area. You can retrieve your items from the Crafter's inventory area. However, you cannot retrieve your items that appear in the Crafter's crafting grid. The moment you left-mouse-click on one of your items that is in one of the nine squares of the Crafter's crafting grid, that item disappears instantly. That is exactly what happens when you want to clear a recipe from the Crafter's crafting grid. You left-mouse-click on ghosted items in the crafting grid to clear it from the grid. The problem is that the Crafter thinks your item is a ghost and clears it from the grid when you left-mouse-click on the item to pull it out of the crafting grid, effectively deleting your item from the world.

**Comment by HugeLol556** [comment]
This sounds just like the issue that was causing a duplication glitch. I don't know if that middle mouse hotkey is the same sorting mod that I was having issues with, but it seems that there are sorting mods that do not recognize the spaces in mod blocks that hold the "image" of the item rather than the item itself. So you keep the item and a placeholder of the item appears. These "image" spaces are typically for other things in that mod, such as white/blacklist spots, or other identifiers.

In the case of my duplication glitch, you could assign the item "image" to white/blacklist slots, but the sorting mod would treat it as a real item and move it into a space where you could remove the item and keep it.

This situation sounds like the opposite. The sorting mod is taking real items, removing them from your inventory, and placing them into "image" slots. And of course, when you try to remove these items, the mod block does what it is supposed to and doesn't give you the item and just makes the image disappear. 

Quick Fix: Go into options and unbind whatever it is that is using middle mouse.

**Comment by whatthedrunk** [comment]
Removed the Inventory sort button middle click for new profiles while adding quarks inventory sort with S. You will probably have to change it manually unless you use a new profile. 

Let me know if the issue still persists after that and we can reopen the issue.
