### ISSUE TITLE
Plant sower is really slow / Range upgrade disappears if middle click in the upgrade slot 1.16a

### ISSUE THREAD

**Issue by darkluzer** [AllTheMods/ATM-5#74]
## Expected Behavior
Plant sower should work if it has energy, I am using a range +10 upgrade on it.

## Current Behavior
Plant sower cant keep up with the crops, it is leaving empty places in the field and its not working all the time, it plants 4-6 seeds and stops for a while, then it plants again and stops. I have enough energy, seeds and the filters are in place.

If you middle click in the upgrade slot all the upgrades will disappear

## Steps to Reproduce

1.Make a field with a plant sower in the middle under the dirt
2.Give it enough energy, seeds and a +10 upgrade
3.Watch it struggle to work

**Comment by HugeLol556** [comment]
That's because the machine waits for long periods of time. Every time it meets a block that it cannot plant a crop on, its work buffer will wait about 2 seconds before trying the next block. However, when there is a row of free spaces, it will only take about half a second for it to plant each crop. I don't know if this is normal behavior.

Typically speed upgrades would help, but this mod currently doesn't have any built-in because previous versions relied on a different mod for speed upgrades.
