### ISSUE TITLE
Seeds not dropping

### ISSUE THREAD

**Issue by PeacefulBunny** [AllTheMods/ATM-5#81]
Seeds not dropping in the 1.17b update.
Not from grass or farmland crops when right clicking.

## Possible Solution

Simple farming could be the mod that causes the issue, i guess.

## Steps to Reproduce

1.
2.
3.
4.

**Comment by utoc** [comment]
I've noticed this as of 1.17a as well and the issue is wildly inconsistent between users and worlds.  If I try to harvest wheat with just a watering can or my hand, I will very rarely ever get a seed drop.  If I use bonemeal, I will get seeds plentifully.  I tried on 1.17b as well and noticed the same issue.  I have one user that harvested two stacks of wheat and only ended up with 5 seeds.  Another user can come right behind them and get seeds plentifully with just their hand.  Its bizarre.  I'm sorry I do not have actual data to present but this has been a weird issue to pinpoint.

I noticed shears do not work on grass either but I'm not sure if this is related.

**Comment by utoc** [comment]
From my debug.log

```
[18Apr2020 13:05:14.849] [Server thread/ERROR] [net.minecraft.world.storage.loot.LootTableManager/]: Couldn't parse loot table minecraft:blocks/grass
```

I also have this error for tall grass and it appears to go back to the Simple Farming mod.

See full debug log here: 
[debug.log](https://github.com/AllTheMods/ATM-5/files/4498120/debug.log)

**Comment by whatthedrunk** [comment]
Thanks. I did have to remove the mod from version 18 to fix the seed drops and shearing grass. It should be out within the hour.
